[package]
name = "tbar"
version = "0.9.0"
authors = ["Vladyslav Kotliar <kotliarvladyslav@gmail.com>"]
edition = "2021"

[dependencies]
ansi_term = "0.12"
zellij-tile = "0.37.0"
zellij-tile-utils = "0.37.0"
